spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: rooot
    url: jdbc:mariadb://localhost:3307/test?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML