spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: rooot
    url: jdbc:mariadb://localhost:3307/test?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/templates/

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.hotel_booking_app.Pojo # type-aliases-package 指定了扫描实体类的位置，就可以省略类的具体路径而直接写类名。不知道UserDetails要不要写路径？
  configuration:
    map-underscore-to-camel-case: false

jwt:
  #  JWT加密使用的密钥
  secret: nothing

server:
  ssl:
    key-store: classpath:tomcat_https.keystore
    key-store-password: cvhrdog
    key-store-type: PKCS12
    key-alias: tomcat_https
    enabled: true
    key-password: cvhrdog
  port: 8081